---

- name: "Uncompress JDK"
  hosts: "tomcat"
  gather_facts: no
  tasks:
    - name: "Create java directory"
      file:
        path: "/opt/java"
        state: directory
    - name: "Unarchive JDK"
      unarchive:
        src: "~/Téléchargements/jdk-8u172-linux-x64.tar.gz"
        dest: "/opt/java"
