---

- name: "Uncompress apache tomcat"
  hosts: "tomcat"
  gather_facts: no
  tasks:
    - name: "Create tomcat directory"
      file:
        path: "/opt/tomcat"
        state: directory
    - name: "Unarchive apache tomcat"
      unarchive:
        src: "~/apache-tomcat-8.5.24.tar.gz"
        dest: "/opt/tomcat"
